### ISSUE TITLE
ToMany

### ISSUE THREAD

**Issue by Reginer** [objectbox/objectbox-examples#26]
Hello，I don't understand how tomany is used in the example.
How do I implement tomany annotations after I use Gsonformat to generate code?

![box1](https://user-images.githubusercontent.com/12568257/32593225-1876895e-c562-11e7-8e9c-cc79ec2cad1f.png)

`{
    "code": 0,
    "data": [
        {
            "city": "City",
            "sign": "Sign"
        },
        {
            "city": "City1",
            "sign": "Sign1"
        }
    ],
    "debugMsg": "",
    "msg": "",
    "pageInfo": {
        "count": 20,
        "hasMore": 0,
        "page": 1,
        "pageCount": 1,
        "total": 2
    }
}`

**Comment by greenrobot-team** [comment]
You also might want to look at [the Relations documentation](http://objectbox.io/documentation/relations/) for a more detailed explanation of relations.

For your to-one relationship use `ToOne<PageInfoEntity>`.

For your to-many relationship using `List<DataEntity>` should work. At runtime it will be a `ToMany<DataEntity>` (`ToMany` implements `List`).

Working with model classes for Gson is currently limited. See https://github.com/objectbox/objectbox-java/issues/104
-ut

**Comment by Reginer** [comment]
ok，I know.
