### ISSUE TITLE
How can I keep the history data when migration variant type

### ISSUE THREAD

**Issue by YuTianTina** [objectbox/objectbox-examples#28]
why I change the variant type like :
int age -> String age

my history age data will be cleaned , how can I keep the data when change the variant type?

**Comment by greenrobot-team** [comment]
**This is not possible** as ObjectBox can not change the type of the data you have already stored. As an alternative you might want to add a differently named field and get data from the old field when accessing it:
```
int age;
String ageText;
```

As for what is possible regarding renaming entities and properties, see the [ObjectBox Data Model Updates](http://objectbox.io/documentation/objectbox-entity-property-migration/) documentation.
-ut

**Comment by YuTianTina** [comment]
ok, thank you
