### ISSUE TITLE
Having greenDao and ObjectBox at the same time

### ISSUE THREAD

**Issue by anna-b** [objectbox/objectbox-examples#32]
I am using greenDAO with Rx queries in my life app now. And I would like to migrate to using ObjectBox instead. I found some documentation about how I should set up the things during migration from one service to another but I find documentation and examples here conficting:
in the objectbox/objectbox-examples you do not include 
compile "io.objectbox:objectbox-android:$objectboxVersion"
annotationProcessor "io.objectbox:objectbox-processor:$objectboxVersion"
into the gradle file, but only
implementation "org.greenrobot:objectbox-daocompat:1.1.0"

At the same time I cannot get the DaoCompatSession to get generated. I still find the reference to the greendDao's DaoSession only.
Do you have an example of the project should be setup when having both greenDao and DaoCompat at the same time? I am sure a lot of people would appreciate it.
Do you have proguard configuration for objectBox and DaoCompat, haven't noticed that you mention it somewhere?

**Comment by greenrobot-team** [comment]
Have a look at the [daocompat example project within this repository](https://github.com/objectbox/objectbox-examples/tree/master/daocompat-example). In addition there is [documentation available](http://greenrobot.org/greendao/documentation/objectbox-compat/).

As to your specific questions:
- If you apply the ObjectBox plugin it adds the io.objectbox dependencies automatically. Adding them yourself is optional.
- The session class is still called `DaoSession`.
- The ObjectBox ProGuard rules are included in the library and applied automatically.

-ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
