### ISSUE TITLE
Objectbox with retrofit

### ISSUE THREAD

**Issue by YehualashetGit** [objectbox/objectbox-examples#35]
I am using ObjectBox and I want to use it retrofit but, I have to parse manually rather than, automatically parsed using Gson.is there a way to automatically parse the ObjectBox model?? Thank you.

**Comment by greenrobot-team** [comment]
Not sure what you are looking for. But maybe https://github.com/objectbox/objectbox-java/issues/104

Otherwise try searching https://github.com/objectbox/objectbox-java/issues or submit a new issue there with an example of what you are trying to do.
-ut
