### ISSUE TITLE
Add data using ObjectBox

### ISSUE THREAD

**Issue by ali-abbas-10p** [objectbox/objectbox-examples#37]
I want to directly enter data into Database using Objectbox browser.
Can you please guide how to do that?

**Comment by greenrobot-team** [comment]
This is currently not possible. The object browser [can only display or download your data](http://objectbox.io/documentation/data-browser/). You should use debug code inside your app to add test data [through the regular API](http://objectbox.io/documentation/how-to-get-started/).
-ut

**Comment by ali-abbas-10p** [comment]
Do you guys have any plans to do that in future release?

**Comment by greenrobot-team** [comment]
Not that I know of. But you could create a feature suggestion at https://github.com/objectbox/objectbox-java/issues and based on how much attention it gets we might consider it. -ut
