### ISSUE TITLE
Support for MacOS desktop

### ISSUE THREAD

**Issue by BukT0p** [objectbox/objectbox-examples#38]
Currently supported platforms are Linux and Windows, but majority of android devs uses MacOS, add  support for Mac users, please!

> if (isLinux64) {
>         compile "io.objectbox:objectbox-linux:$objectboxVersion"
>     } else if (isWindows64) {
>         compile "io.objectbox:objectbox-windows:$objectboxVersion"
>     } else println("Native dependency could not be set up for unsupported OS: " + osName)

**Comment by greenrobot-team** [comment]
See https://github.com/objectbox/objectbox-java/issues/19. -ut
