### ISSUE TITLE
can't generate MyObjectBox class...

### ISSUE THREAD

**Issue by ShuttleSpace** [objectbox/objectbox-examples#39]
My Project has three modules include main module(app) and common module、chat module.
the app module and other module rely on the common module because  I put all of the 3rd dependencies in it,also other common codes.

But I can't find the MyObjectBox class after build the project.so I put the dependencies in all three modules, but when I build the project it throw the exception: 
> Multiple dex files define Lio/objectbox/android/AndroidObjectBrowserReceiver;

So,how to fix this?
Early thanks...

**Comment by greenrobot-team** [comment]
You can apply the ObjectBox plugin to only one module in your project. As the plugin automatically adds required dependencies, if you add it to multiple modules it will lead to conflicts. -ut

**Comment by greenrobot-team** [comment]
No response. Closing. -ut
