### ISSUE TITLE
Can‘t find MyObjectBox 

### ISSUE THREAD

**Issue by OnlyYouMyLove** [objectbox/objectbox-examples#40]
project build.gradle:

`buildscript {
    ext.objectboxVersion = '1.4.3'
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "io.objectbox:objectbox-gradle-plugin:$objectboxVersion"
    }
}`

app build.gradle:
`apply plugin: 'io.objectbox'`

Can't find MyObjectBox !

**Comment by greenrobot-team** [comment]
Make sure to build the project. `MyObjectBox` is a generated class.

See the [Instructions docs](http://objectbox.io/documentation/introduction/) to get started.
-ut
