### ISSUE TITLE
Annotation processor fails at Eclipse

### ISSUE THREAD

**Issue by FlasH-RUS** [objectbox/objectbox-examples#41]
Hi, tried to switch to ObjectBox one of my hobby projects and realized its annotation processing doesn't work with Eclipse :(

Steps to reproduce:
1. Clone this repo.
2. Add `apply plugin: 'net.ltgt.apt-eclipse'` and `apply plugin: 'eclipse'` into _build.gradle_ of _java-main_.
3. Do `gradlew cleanEclipse eclipse`.
4. Open the projects in Eclipse.

**Expected result**: generated sources appear in _.apt_generated_ folder.
**Actual result**: they are not and the error log shows the "dir.parentFile must not be null" error (see full stacktrace [here](https://github.com/objectbox/objectbox-examples/files/2019796/stacktrace.log) ).

SO states File.getParentPath() returning _null_ may be fixed with adding _getAbsoluteFile()_ before it: `dir.getAbsoluteFile().getParentPath()` - is it the case?

## Tech details
eclipse.buildId=4.8.0.I20180308-0630
java.version=1.8.0_171
java.vendor=Oracle Corporation
OS: Ubuntu 18.04 x64
Project root: $HOME/git/objectbox-examples

**Comment by greenrobot-team** [comment]
Thanks for reporting. The annotation processor is actually running, but fails. There is a bug on our side that prevents an error message to be shown. The actual issue is that the processor can not find the build folder (by default) to write the model file into.

- Can you look for a file named `objectbox-build-config.json` and what directory it is in?
- Try to run the default Gradle `clean` and `build` tasks instead of `cleanEclipse eclipse`.

As a temporary workaround you can [manually specify the model file path](http://objectbox.io/documentation/advanced-objectbox-setup/).
-ut

**Comment by FlasH-RUS** [comment]
> We track issues with ObjectBox itself at https://github.com/objectbox/objectbox-java/issues

That's more gradle plugin related, but since it's not in github I placed it here. My bad. Anyway I guess we can continue here for this one?

Back to the topic. Project structure is like that:
```
.
├── build.gradle
├── app
│   ├── build
│   ├── build.gradle
│   └── ...
├── domain
│   ├── build
│   ├── build.gradle
│   ├── objectbox-models
│   └── src
├── gradle
│   └── wrapper
├── gradle.properties
├── gradlew
├── gradlew.bat
└── settings.gradle
```
_domain_ is the module with ObjectBox entities and nothing more (and the only module with ObjectBox gradle plugin applied), _app_ is the one where all the app code is.
`objectbox-build-config.json` is in `domain/build/`.

`./gradlew clean build` works perfectly, the only problem is ObjectBox annotation processor failures from Eclipse itself. My workaround was first to separate all the entities to a separate module and second - include this module jar as a dependency especially for eclipse:
In `domain/build.gradle`:
```
eclipse.classpath.file.whenMerged {
    classpath ->
      classpath.entries.add(new org.gradle.plugins.ide.eclipse.model.SourceFolder('build/generated/source/apt/main', null))
}
```
In `app/build.gradle`:
```
eclipse.classpath.file {
    whenMerged { classpath ->
      def lib = new org.gradle.plugins.ide.eclipse.model.Library(fileReference(file("../domain/build/libs/domain-${project.version}.jar")))
      lib.exported = true
      classpath.entries << lib
    }
}
```
Not very convenient (have to `./gradlew domain:assemble` every time you change anything in _domain_), but at least works.

The same problem reproduces with your _java-main_ example also - I can (in some time) fork it to apply eclipse support there so you'll have a live example if it helps :)

**Comment by greenrobot-team** [comment]
Gradle 5.2 now has full annotation processor support making the apt plugin unnecessary.

IntelliJ IDEA 2019.1 delegates build-actions and test runs to Gradle 5.2 or newer. It's up to Eclipse to ensure compatibility here, nothing for use to do anymore.
