### ISSUE TITLE
How to find object with maximum value of property?

### ISSUE THREAD

**Issue by paynd** [objectbox/objectbox-examples#46]
How to find object with maximum value of property?
Now I'm just sorting query result and get first result.
```java
builder.equal(SomeEntity_.prop, entity.prop).sort(comparator).build().find().get(0);
```

**Comment by greenrobot-team** [comment]
You might be able to use an order instead and just get the first result:
`.order(Note_.id, QueryBuilder.DESCENDING).build().findFirst()`

You might have to add additional flags, like `NULLS_ZERO`. Check the docs of the order method.

Closing. Please re-open if your question was not answered.
-ut
