### ISSUE TITLE
Compile failed after add @Uid 

### ISSUE THREAD

**Issue by SunmerCho** [objectbox/objectbox-examples#49]
I want to test rename the module Properties use @Uid follow the docs, but it b；uild error and not tell you the uids like docs, it show compile failed, it work well if i don't use @Uid；
Here is my error message:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileAutomationDebugJavaWithJavac'
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.

**Comment by greenrobot-team** [comment]
Look at the message above in the output log.

Or if you are using Android Studio select the error in the Build tab:

![image](https://user-images.githubusercontent.com/13865709/45607967-3a1e1480-ba50-11e8-8245-94a88ef61792.png)

Or enable text-only output:
![image](https://user-images.githubusercontent.com/13865709/45607989-5a4dd380-ba50-11e8-8cd9-4c9e8125b6cb.png)

Closing. Please re-open if your question was not answered.
-ut
