### ISSUE TITLE
Feature Request: Support for Flutter

### ISSUE THREAD

**Issue by townsfolk** [objectbox/objectbox-examples#50]
I've been using Flutter (Dart) for a few projects, and really missed the ease-of-use that comes with ObjectBox. When I saw the awesome news of ObjectBox for Swift, it made me think there may be some possibility for either a port to Dart, or a bridge-like library which lets your Flutter app use ObjectBox-Swift on IOS, and ObjectBox-Java on Android.

**Comment by greenrobot-team** [comment]
See https://github.com/objectbox/objectbox-java/issues/558
-ut
