### ISSUE TITLE
我用java-main-maven 来运行,但是很明显,抛出了空指针异常,这个例子应该是有问题的.

### ISSUE THREAD

**Issue by 17097201102** [objectbox/objectbox-examples#54]
![Uploading image.png…]()

**Comment by 17097201102** [comment]
<img width="825" alt="Snipaste_2019-10-24_17-45-48" src="https://user-images.githubusercontent.com/31331702/67474078-6d38cb80-f686-11e9-8011-6ade6001e56a.png">

**Comment by greenrobot-team** [comment]
@17097201102 What was the issue? Did you forget to add the `pluginRepository`?

https://github.com/objectbox/objectbox-examples/blob/ca9ac77d12a5033be1b26a1c77183088bbfc358c/java-main-maven/pom.xml#L45-L60
