### ISSUE TITLE
Why to null box in the test example

### ISSUE THREAD

**Issue by emartynov** [objectbox/objectbox-examples#56]
https://github.com/objectbox/objectbox-examples/blob/555df0d43d39f1132ace397613777ae6e1f0cbb5/android-app/src/test/java/io/objectbox/example/AbstractObjectBoxTest.java#L36

The junit will create a new test class for every test. So you don't need to null store in the tear down.

**Comment by greenrobot-team** [comment]
This is to catch programming errors, so no other code uses `store` after it has been closed.

**Comment by emartynov** [comment]
Clear, you will still get an error in this case. But it is a matter of the taste what kind of error you want to see in this case.
