### ISSUE TITLE
bintray-objectbox-objectbox

### ISSUE THREAD

**Issue by 137303553322** [objectbox/objectbox-examples#58]
<pluginRepositories>
        <pluginRepository>
            <id>bintray-objectbox-objectbox</id>
            <name>bintray-plugins</name>
            <url>https://dl.bintray.com/objectbox/objectbox</url>
        </pluginRepository>
    </pluginRepositories>

Address unavailable

**Comment by greenrobot-team** [comment]
Thanks, tracking this with https://github.com/objectbox/objectbox-java/issues/1041
